version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: jboss/keycloak
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        KEYCLOAK_IMPORT: /tmp/tenant_1.json,/tmp/tenant_2.json -Dkeycloak.profile.feature.upload_scripts=enabled
      volumes:
        - "./realms:/tmp"
      ports:
        - 8080:8080
      depends_on:
        - postgres
  consul:
    image: consul:latest
    ports:
      - 8500:8500
    command: agent -server -bootstrap-expect 1 -ui -data-dir /tmp -client=0.0.0.0
    entrypoint:
      - consul

  system-config:
    build:
      context: ./config
      dockerfile: Dockerfile
    ports:
      - 9999:9999

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    depends_on:
      - system-config
      - consul
      - keycloak
    ports:
      - 8089:8089

  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    depends_on:
      - gateway
      - system-config
      - consul
      - keycloak

  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile
    depends_on:
      - gateway
      - system-config
      - consul
      - keycloak

  frontend:
    build:
      context: ./frontend/src/main/angular-oauth2
      dockerfile: Dockerfile
    depends_on:
      - gateway
      - system-config
      - consul
      - keycloak
    ports:
      - 4200:80

   
